### ISSUE TITLE
Can’t INSERT "DROP TABLE 😎"

### ISSUE THREAD

**Issue by ApolloZhu** [CaptainYukinoshitaHachiman/BirthReminder#13]
WHERE IS Unicode support?

**Comment by uetcis** [comment]
Well, I've got no idea with this bug. According to the log file on my backend, there seem to be something wrong with the MySQL insertion, and I'm wondering if this is a bug of PerfectMySQL.

**Comment by uetcis** [comment]
Also, if you're interested in it, you may check out [the backend](https://github.com/CaptainYukinoshitaHachiman/BirthReminder-Backend/blob/master/Sources/BirthReminderBackend/Contributing.swift#L46) for further.

**Comment by uetcis** [comment]
Issue resolved by setting the charset to `utf8mb4` in MySQL
ref: https://blog.csdn.net/u013145194/article/details/51527389
