### ISSUE TITLE
Could you change this fxxking background colour?

### ISSUE THREAD

**Issue by flandia** [CaptainYukinoshitaHachiman/BirthReminder#16]
Or maybe provides an option that changes the background colour, like [Dai-Hentai](https://github.com/DaidoujiChen/Dai-Hentai).

**Comment by uetcis** [comment]
UI redesign is under consideration, thanks for your advice!

**Comment by ApolloZhu** [comment]
I actually agree with this

**Comment by uetcis** [comment]
Orz

**Comment by uetcis** [comment]
@ApolloZhu @1793907272 

I'll try to design a better UI using Sketch while taking tomorrow's workshop

<img width="340" alt="image" src="https://user-images.githubusercontent.com/25654046/39407865-9cd68dec-4bff-11e8-9dbd-b59cd97e6d30.png">

Moreover, I've updated [the board for this](https://github.com/CaptainYukinoshitaHachiman/BirthReminder/projects/1#column-1646034)

**Comment by flandia** [comment]
@CaptainYukinoshitaHachiman Have you finished your designing? There is 17 mins left.
