### ISSUE TITLE
[Proposal] Solving "Minimum Functionality"

### ISSUE THREAD

**Issue by ApolloZhu** [CaptainYukinoshitaHachiman/BirthReminder#6]
- [ ] Integrate SiriKit

> Hey Siri, when's Yukino Yukinoshita's birthday?

- [ ] Integrate Social Framework
  - [ ] Generate Birthday Post
  - [ ] If an image is present, generate a birthday card
    - [ ] If ARKit available, hmmm...

- [ ] Integrate Contacts Framework
  - [ ] If present, add info
  - [ ] Otherwise, create a new contact

**Comment by uetcis** [comment]
Thanks for advising.
Some of the things above are really amazing, and I’ll try to add them into this app.

Also, I’ve got some ideas about new features, you may check it in projects.

(´▽｀)

**Comment by uetcis** [comment]
BTW, I don’t think it will be wonderful if we integrate ARKit within this app because.....

![0c399f0c-672b-4edc-99be-9dff69720bc3](https://user-images.githubusercontent.com/25654046/31854203-d6eea24e-b6c7-11e7-96aa-be6f17c0c1a0.jpeg)

**Comment by ApolloZhu** [comment]
So tru. Let me sleep on this
![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/20170813_Grape_and_Hululu_at_Tobu_zoo.jpg/320px-20170813_Grape_and_Hululu_at_Tobu_zoo.jpg)
